---
title: "EDS 223 Assignment 1: Cartography "
author: "Mia Forsline and Brendan Mcgovern"
date: "9/25/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(RColorBrewer)
#display.brewer.all(colorblindFriendly = T)

library(rgeos)
library(rnaturalearth)
library(rnaturalearthdata)
library(sf)
library(spData)
library(spDataLarge)
library(tidyverse)
library(tmap)
library(dplyr)
```

# data from `spData`
```{r}
world
world_asia <- world[world[["continent"]] == "Asia", ]
china <- world[world[["name_long"]] == "China", ]

#transform coordinate system if necessary 
#sf::st_transform(your_object, new_crs)
```

# Exploratory plots using base `plot` 
```{r}
plot(world_asia, max.plot = 10) #multi-plot of all attributes
plot(world_asia["gdpPercap"], 
     key.pos = 4) #set the color key position (1=below, 2=left, 3=above and 4=right):

plot(world_asia["gdpPercap"], 
     key.pos = 1, 
     axes = TRUE, #lat/long tick marks 
     key.width = lcm(1.3), 
     key.length = 1.0)
```

## Specify class intervals 
- what does the distribution of data look like ? 
```{r}
plot(world_asia["gdpPercap"], nbreaks = 10)
#nbreaks specifices # of breaks
#breaks uses a vector to specify break values or the break style 
plot(world_asia["gdpPercap"], breaks = "jenks")
```
# Graticule
```{r}
plot(world_asia["gdpPercap"], graticule = TRUE, key.pos = NULL, axes = TRUE)
# standard WGS84 
```

# `tmap` 
```{r}
bbox_new <- st_bbox(c(xmin = 0, xmax = 179.99999,
                      ymin = -85, ymax = 83.64513 ))
xrange <- bbox_new$xmax - bbox_new$xmin # range of x values
yrange <- bbox_new$ymax - bbox_new$ymin # range of y values
bbox_new <- bbox_new %>%  # take the bounding box ...
  st_as_sfc()

#world map with Asia GDP per capita colored red 
inset <- tm_shape(world, bbox = bbox_new)+
  tm_fill() + 
  tm_borders(lwd = 0.1) + 
tm_shape(world_asia) +
  tm_fill(col = "gdpPercap", 
          palette = "Reds", 
          style = "quantile",
          colorNA = "gray",
          legend.show = FALSE) +
  tm_borders(lwd = 0.5) + 
  tmap_options(bg.color = "lightblue1")
inset
```

# Create a new bounding
```{r}
bbox_new <- st_bbox(world_asia) # current bounding box
xrange <- bbox_new$xmax - bbox_new$xmin # range of x values
yrange <- bbox_new$ymax - bbox_new$ymin # range of y values
bbox_new <- bbox_new %>%  # take the bounding box ...
  st_as_sfc()

#Asia map 
asia_map <- tm_shape(world, bbox = bbox_new)+
  tm_fill(col = "white") + 
  tm_borders(lwd = 0.1) + 
tm_shape(world_asia) +
  tm_borders(lwd = 0.1) +
  tm_fill(col = "gdpPercap", 
          palette = "YlOrRd", 
          style = "quantile",
          title = "GDP Per Capita",
          textNA = "Missing Data",
          colorNA = "gray") +
  tm_compass(type = "4star", 
             position = c("right", "center"), 
             size = 4, 
             show.labels = 2) + #show NESW 
  #compass types: arrow, 4star, 8star, radar, rose
  tm_scale_bar(breaks = c(0, 1000, 2000), 
               text.size = 1, 
               position = c("center", "bottom")) + 
  tm_text(text = "name_long", 
          size = 0.7, 
          col = "black") + 
  tm_layout(scale = 0.6, #zoom in and out 
            frame.lwd = 5,
            "GDP Per Capita in Asia",
            legend.text.size = 1,
            legend.title.size = 1.5, 
            legend.position = c("left", "bottom"),
            legend.bg.color = "white",
            legend.frame = "black", 
            title.size = 1.3) + 
  tmap_options(bg.color = "lightblue1")+ 
  tm_credits("GDP per capita for each country in the AOriginal data from spData.", 
             position=c("right", "bottom"),
             #bg.color = "white", 
             #bg.alpha = 0.5, 
             size = 0.5)
asia_map
tmap_save(filename = "asiamap.jpg", width = 8, height = 5, units = "in", dpi = 300)
```

# Place inset map 
```{r}
library(grid)
asia_map
vp = viewport(0.87, 0.235, width = 0.3, height = 0.3)
print(inset, vp = viewport(0.87, 0.235, width = 0.3, height = 0.3))
tmap_save(asia_map, 
          filename = "inset.jpg", 
          width = 8, height = 5, units = "in", dpi = 300, 
          insets_tm = inset,
          insets_vp = vp)

```





## China inset map ?? 
```{r}
china

china_inset = st_bbox(c(xmin = 73.67538, xmax = 135.0263,
                      ymin = 18.1977 , ymax = 53.4588),
                      crs = st_crs(china$pop)) %>% 
                      st_as_sfc() 
china_inset

asia_map = tm_shape(world_asia) + 
  tm_polygons()+
  tm_scale_bar(position = c("left", "bottom"))
asia_map

asia_inset = tm_shape(world_asia) +  tm_polygons() +
  tm_shape(china_inset) + 
  tm_borders(lwd = 1) 
asia_inset

library(grid)
asia_map
print(asia_inset, vp = viewport(1, 0.3, width = 0.5, height = 0.5))

#tmap_save()
```


```{r}
vignette('rnaturalearth', package='rnaturalearth')
vignette('what-is-a-country', package='rnaturalearth')
```

# `rnaturalearth` package 
```{r}
#world countries from `rnaturalearth` package 
sp::plot(ne_countries())

#specific country 
sp::plot(ne_countries(country = 'china'))
#specific continent
sp::plot(ne_countries(continent = 'asia'))
```

```{r}
china <- ne_countries(country = 'china')
asia <- ne_countries(continent = 'asia')
```

